### PR TITLE
chore: fix web nft linker example doesn't work

### LINKED ISSUE #110: missing assets in 'send NFTs' examples-web
GET http://localhost:3000/assets/Ethereum.gif 404 (Not Found)          
GET http://localhost:3000/assets/Avalanche.gif 404 (Not Found)

### LINKED ISSUE #111: send NFT example in `examples-web` doesn't work
Click on "send" and the NFT disappears from the source chain, but doesn't appear on the destination chain.

### PR DESCRIPTION
**Pull request by npty**
# Description

- Closes #111 
- Closes #110 

This PR addresses the NFT linker example issue by ensuring the same salt is used for deployment, which allows for consistent contract addresses across different chains. This is necessary due to the contract's source address check requiring a match with its own address.

# Other Changes
- Updated the deployment method to `deployCreate3Upgradable` to showcase this new deployment approach.
- Updated to use `@typechain/hardhat` to generate type automatically after the compilation step, eliminating the need for an additional command to be run explicitly.

### CODE REVIEW

File: examples-web/scripts/nft-linker/deploy.ts [hunk 1]
```diff
@@ -28,25 +28,28 @@ export async function deploy(wallet: Wallet, chainA: any, chainB: any) {
...
+    chainB.create3Deployer,
     walletB,
     NFTLinker,
     ExampleProxy,
     [chainB.gateway, chainB.gasService],
     [],
     utils.defaultAbiCoder.encode(['string'], [chainB.name]),
+    salt
   );
   chainB.nftLinker = nftLinkerB.address;
```
Comment (npty) [inline examples-web/scripts/nft-linker/deploy.ts:55]: These changes fix the NFT Linker issue

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Not working for me. Followed readme from scratch as usual:
```
$ npm run deploy

> axelar-example-web@0.1.0 deploy
> run-s contracts:build contracts:deploy


> axelar-example-web@0.1.0 contracts:build
> hardhat compile

Generating typings for: 3 artifacts in dir: src/types for target: ethers-v5
Successfully generated 56 typings!
Compiled 3 Solidity files successfully

> axelar-example-web@0.1.0 contracts:deploy
> ts-node scripts/deploy-contracts.ts

/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/types/factories/contracts/call-contract/index.ts:4:42 - error TS2307: Cannot find module './MessageReceiver__factory' or its corresponding type declarations.

4 export { MessageReceiver__factory } from "./MessageReceiver__factory";
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/types/factories/contracts/call-contract/index.ts:5:40 - error TS2307: Cannot find module './MessageSender__factory' or its corresponding type declarations.

5 export { MessageSender__factory } from "./MessageSender__factory";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1411:41)
    at Module.m._compile (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1596:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2307, 2307 ]
}
ERROR: "contracts:deploy" exited with 1.
```

**Comment by npty** [comment]
> MessageReceiver__factory

Could you pull the branch and retry `npm run deploy` command to see if that works for you?

**Review by StephenFluin — APPROVED** [review]
LGTM!
